//! The verb census: which QML components each verify-ui line leaves
//! standing, recorded by the runs themselves.
//!
//! The harness walks the window's item tree as the run finishes and
//! reports every QML type it met (`WindowCensus.qml`); a passing run
//! writes them here against the line that ran it. The gate then owes a
//! verb for a QML change when the verb's census names a file the change
//! reaches — a mechanical answer to "which verbs show this", with no
//! table anyone writes by hand. A file the census never names is one no
//! verb shows, and the gate says so rather than passing it.
//!
//! **A run rewrites its line rather than adding to it.** The walk is one
//! walk on the run's own edge, so a line is a function of the build and
//! the verb; keeping names no run reproduces would leave the gate
//! selecting verbs for components they stopped showing, and would call a
//! component covered that nothing brings up any more. The file is a
//! snapshot: regenerated by the runs, reviewed as a diff, never edited by
//! hand.
//!
//! Only lines that are reproducible are recorded: a run against a `--repo`
//! of this machine names nothing another machine has.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use super::graph::{collect, stem_of};

/// Where the census lives, checked in beside the runner so a fresh clone
/// knows what the verbs show. Rewritten by runs, never by hand.
pub(crate) const FILE: &str = "crates/xtask/verb-census.txt";

const HEADER: &str = "\
# The verb census — written by `cargo xtask verify-ui`, read by `cargo xtask gate`.
#
# One line per verify-ui argument line that passed, followed by a tab and
# the QML components (ui/ and auto/, by file name) the window was showing
# as the run finished. The gate owes a change every verb whose census
# names a file the change reaches. A run rewrites its own line, and a name
# whose file is gone leaves every line on the next write. Never edited by
# hand: run the verb instead, and this file follows.
";

#[derive(Default)]
pub(crate) struct Census {
    /// verify-ui line -> the component names its run met.
    pub lines: BTreeMap<String, BTreeSet<String>>,
}

impl Census {
    pub(crate) fn load(root: &Path) -> Census {
        let text = std::fs::read_to_string(root.join(FILE)).unwrap_or_default();
        let mut census = Census::default();
        for line in text.lines() {
            if line.starts_with('#') || line.trim().is_empty() {
                continue;
            }
            let Some((key, names)) = line.split_once('\t') else {
                continue;
            };
            census.lines.insert(
                key.to_string(),
                names.split_whitespace().map(str::to_string).collect(),
            );
        }
        census
    }

    /// Every recorded line whose run met one of `stems`.
    pub(crate) fn verbs_touching(&self, stems: &BTreeSet<String>) -> Vec<String> {
        self.lines
            .iter()
            .filter(|(_, names)| names.iter().any(|name| stems.contains(name)))
            .map(|(line, _)| line.clone())
            .collect()
    }

    /// Whether any run ever met `stem`.
    pub(crate) fn covers(&self, stem: &str) -> bool {
        self.lines.values().any(|names| names.contains(stem))
    }

    fn save(&self, root: &Path) -> Result<(), String> {
        let mut text = String::from(HEADER);
        for (line, names) in &self.lines {
            text.push_str(line);
            text.push('\t');
            text.push_str(&names.iter().cloned().collect::<Vec<_>>().join(" "));
            text.push('\n');
        }
        let path = root.join(FILE);
        std::fs::write(&path, text).map_err(|e| format!("{}: {e}", path.display()))
    }
}

/// Records what a passing run of `line` showed. Names that are no QML
/// file of the app (C++ types, inline components, files since removed)
/// are dropped; what is left is the line, in place of whatever an earlier
/// run of it wrote.
pub(crate) fn record(root: &Path, line: &str, names: &[String]) -> Result<usize, String> {
    let known = component_files(root)?;
    let mut census = Census::load(root);
    let shown: BTreeSet<String> = names
        .iter()
        .filter(|n| known.contains(*n))
        .cloned()
        .collect();
    let count = shown.len();
    census.lines.insert(line.to_string(), shown);
    for names in census.lines.values_mut() {
        names.retain(|name| known.contains(name));
    }
    census.save(root)?;
    Ok(count)
}

/// The names of every QML component file of the app, product and
/// harness alike.
fn component_files(root: &Path) -> Result<BTreeSet<String>, String> {
    let mut files = Vec::new();
    collect(
        root,
        &root.join("crates/platitude-app/src"),
        "qml",
        &mut files,
    )?;
    Ok(files.iter().map(|f| stem_of(f)).collect())
}

/// Whether a QML file can stand in the item tree at all. A singleton or a
/// `QtObject` root never does, so no census can name it: its readers
/// carry it.
pub(crate) fn instantiable(root: &Path, file: &str) -> bool {
    let Ok(text) = std::fs::read_to_string(root.join(file)) else {
        return false;
    };
    if text.contains("pragma Singleton") {
        return false;
    }
    let code = super::graph::strip_comments(&text);
    // The root type is the first word of the first line that opens an
    // object: `Item {`, `QtObject {`, `AppCard {`.
    let root_type = code
        .lines()
        .map(str::trim)
        .find(|line| line.ends_with('{') && !line.starts_with("import") && !line.contains(':'))
        .and_then(|line| line.split_whitespace().next())
        .unwrap_or("");
    root_type != "QtObject"
}

/// The names a run reported: the `census=` line, comma-separated.
pub(crate) fn names_in(lines: &[String]) -> Option<Vec<String>> {
    lines
        .iter()
        .rev()
        .find_map(|line| line.split("census=").nth(1))
        .map(|rest| {
            rest.trim()
                .split(',')
                .map(str::trim)
                .filter(|n| !n.is_empty())
                .map(str::to_string)
                .collect()
        })
}

#[cfg(test)]
mod tests {
    use super::{Census, names_in, record};
    use std::collections::BTreeSet;
    use std::path::PathBuf;
    use std::sync::atomic::{AtomicU64, Ordering};

    /// A root holding nothing but the QML files a census may name.
    fn root_with(components: &[&str]) -> PathBuf {
        static NEXT: AtomicU64 = AtomicU64::new(0);
        let serial = NEXT.fetch_add(1, Ordering::Relaxed);
        let root = std::env::temp_dir().join(format!("pg-census-{}-{serial}", std::process::id()));
        let ui = root.join("crates/platitude-app/src/ui");
        std::fs::create_dir_all(&ui).expect("ui dir");
        std::fs::create_dir_all(root.join("crates/xtask")).expect("xtask dir");
        for name in components {
            std::fs::write(ui.join(format!("{name}.qml")), "Item {}\n").expect("component");
        }
        root
    }

    #[test]
    fn owes_the_verbs_whose_runs_met_a_reached_file() {
        let mut census = Census::default();
        census.lines.insert(
            "commit --preset basic".into(),
            ["CommitBox", "GraphPane"].map(String::from).into(),
        );
        census.lines.insert(
            "diff-file notes.txt".into(),
            ["DiffPane"].map(String::from).into(),
        );
        let reached: BTreeSet<String> = ["DiffPane".to_string()].into();
        assert_eq!(census.verbs_touching(&reached), vec!["diff-file notes.txt"]);
        assert!(census.covers("GraphPane"));
        assert!(!census.covers("SettingsDialog"));
    }

    #[test]
    fn reads_the_census_line_a_run_reported() {
        let lines = vec![
            "2026-09-02T01:18:33Z  INFO bench: auto_act ran=commit".to_string(),
            "2026-09-02T01:18:33Z  INFO bench: census=AppCard,DiffPane,Main".to_string(),
        ];
        assert_eq!(
            names_in(&lines),
            Some(vec!["AppCard".into(), "DiffPane".into(), "Main".into()])
        );
        assert_eq!(names_in(&[]), None);
    }

    #[test]
    fn a_run_writes_its_line_over_the_one_before_it() {
        let root = root_with(&["DiffPane", "GraphPane", "WipPane"]);
        record(
            &root,
            "wip --preset dirty",
            &["GraphPane".into(), "WipPane".into()],
        )
        .expect("first");
        // The verb stopped showing the graph and started showing the
        // diff: what it shows now is the whole of its line.
        let count = record(
            &root,
            "wip --preset dirty",
            &["DiffPane".into(), "WipPane".into(), "QQuickText".into()],
        )
        .expect("second");
        assert_eq!(count, 2, "a name that is no QML file of the app is dropped");
        let census = Census::load(&root);
        assert_eq!(
            census.lines["wip --preset dirty"],
            ["DiffPane", "WipPane"].map(String::from).into()
        );
        assert!(!census.covers("GraphPane"), "no run shows it any more");
    }

    #[test]
    fn a_component_that_is_gone_leaves_every_line() {
        let root = root_with(&["DiffPane", "WipPane"]);
        record(&root, "wip --preset dirty", &["WipPane".into()]).expect("wip");
        record(
            &root,
            "diff-file b.txt",
            &["DiffPane".into(), "WipPane".into()],
        )
        .expect("diff");
        std::fs::remove_file(root.join("crates/platitude-app/src/ui/WipPane.qml")).expect("remove");
        record(&root, "diff-file b.txt", &["DiffPane".into()]).expect("again");
        let census = Census::load(&root);
        assert!(!census.covers("WipPane"));
        assert_eq!(
            census.lines["wip --preset dirty"],
            BTreeSet::new(),
            "the line the run did not touch is pruned too"
        );
    }
}
