//! The verb census: which QML components each verify-ui line leaves
//! standing, recorded by the runs themselves.
//!
//! The harness walks the window's item tree as the run finishes and
//! reports every QML type it met (`WindowCensus.qml`); a passing run
//! writes them here against the line that ran it. The gate then owes a
//! verb for a QML change when the verb's census names a file the change
//! reaches — a mechanical answer to "which verbs show this", with no
//! table anyone writes by hand. A file the census never names is one no
//! verb shows, and the gate says so rather than passing it.
//!
//! **A run whose page had stopped arriving rewrites its line rather than
//! adding to it.** The walk is one walk on the run's own edge, so such a
//! line is a function of the build and the verb; keeping names no run
//! reproduces would leave the gate selecting verbs for components they
//! stopped showing, and would call a component covered that nothing
//! brings up any more. The file is a snapshot: regenerated by the runs,
//! reviewed as a diff, never edited by hand.
//!
//! **A run whose page was still arriving adds to its line instead.** A
//! verb whose subject is the window is finished while the repository is
//! being read, so its lists hold whatever had come and its walk can only
//! say what it did meet — never that the rest is gone
//! (`WindowCensus.pageSettled`, which measured the rates). Writing such a
//! run's line would move a checked-in file under the machine's timing
//! rather than under a change, and the gate that rewrites the census
//! would then demand a commit of the flutter every time it ran.
//!
//! Only lines that are reproducible are recorded: a run against a `--repo`
//! of this machine names nothing another machine has.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use super::graph::{collect, stem_of};

/// Where the census lives, checked in beside the runner so a fresh clone
/// knows what the verbs show. Rewritten by runs, never by hand.
pub(crate) const FILE: &str = "crates/xtask/verb-census.txt";

const HEADER: &str = "\
# The verb census — written by `cargo xtask verify-ui`, read by `cargo xtask gate`.
#
# One line per verify-ui argument line that passed, followed by a tab and
# the QML components (ui/ and auto/, by file name) the window was showing
# as the run finished. The gate owes a change every verb whose census
# names a file the change reaches. A run whose page had stopped arriving
# rewrites its own line and one whose page was still arriving adds to it,
# and a name whose file is gone leaves every line on the next write.
# Never edited by hand: run the verb instead, and this file follows.
";

#[derive(Default)]
pub(crate) struct Census {
    /// verify-ui line -> the component names its run met.
    pub lines: BTreeMap<String, BTreeSet<String>>,
}

impl Census {
    pub(crate) fn load(root: &Path) -> Census {
        Census::parse(&std::fs::read_to_string(root.join(FILE)).unwrap_or_default())
    }

    pub(crate) fn parse(text: &str) -> Census {
        let mut census = Census::default();
        for line in text.lines() {
            if line.starts_with('#') || line.trim().is_empty() {
                continue;
            }
            let Some((key, names)) = line.split_once('\t') else {
                continue;
            };
            census.lines.insert(
                key.to_string(),
                names.split_whitespace().map(str::to_string).collect(),
            );
        }
        census
    }

    /// Every recorded line whose run met one of `stems`.
    pub(crate) fn verbs_touching(&self, stems: &BTreeSet<String>) -> Vec<String> {
        self.lines
            .iter()
            .filter(|(_, names)| names.iter().any(|name| stems.contains(name)))
            .map(|(line, _)| line.clone())
            .collect()
    }

    /// Whether any run ever met `stem`.
    pub(crate) fn covers(&self, stem: &str) -> bool {
        self.lines.values().any(|names| names.contains(stem))
    }

    fn save(&self, root: &Path) -> Result<(), String> {
        let mut text = String::from(HEADER);
        for (line, names) in &self.lines {
            text.push_str(line);
            text.push('\t');
            text.push_str(&names.iter().cloned().collect::<Vec<_>>().join(" "));
            text.push('\n');
        }
        let path = root.join(FILE);
        // Whole or not at all: a run killed between the truncate and the
        // write would leave half a census in the tree, which reads as
        // every later line gone and which the gate would then ask for a
        // commit of. Staged under target/, where git does not look, and
        // moved into place in one step.
        let staging = root.join("target").join("verb-census.txt.part");
        if let Some(dir) = staging.parent() {
            std::fs::create_dir_all(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
        }
        std::fs::write(&staging, text).map_err(|e| format!("{}: {e}", staging.display()))?;
        std::fs::rename(&staging, &path).map_err(|e| format!("{}: {e}", path.display()))
    }
}

/// How many verb lines a moved name is named by before the row counts
/// them instead. A run that starts or stops meeting a component moves
/// its own line, or the handful of lines whose verbs land the same way;
/// a component the app gained or lost moves every line there is. The
/// rows a reader is here for are the first kind, and past a handful the
/// names stop being a row and become the file again.
const NAMED_AT_MOST: usize = 6;

/// What a write did to the census, read as sets rather than as a diff.
///
/// A component the app gained is a name every run meets, so the diff of
/// the file is the whole file — hundreds of lines all saying the one
/// thing, and the single line that gained a name by itself is a needle
/// in them. That line is the one worth reading: it is a verb landing
/// where it did not land before, and as text it looks exactly like the
/// bulk around it. So the write says what it did by name: a name every
/// line moved is one row that counts them, and a name a handful of lines
/// moved is a row that says which verbs.
#[derive(Default)]
pub(crate) struct Shift {
    /// name -> the verb lines whose run met it and had not before.
    gained: BTreeMap<String, BTreeSet<String>>,
    /// name -> the verb lines that had met it and did not this time.
    lost: BTreeMap<String, BTreeSet<String>>,
    /// Verb lines the write put in, against how many names each brought.
    /// Their names are no row of their own: a line that was not there
    /// gained all of them, which the line itself already says.
    put_in: BTreeMap<String, usize>,
    /// Verb lines the write took away, for the same reason.
    took_away: BTreeSet<String>,
    /// How many lines the census holds now, which the counts read against.
    lines: usize,
}

impl Shift {
    /// The sets one census holds against another's.
    pub(crate) fn between(before: &Census, after: &Census) -> Shift {
        let mut shift = Shift {
            lines: after.lines.len(),
            ..Shift::default()
        };
        for (line, names) in &after.lines {
            let Some(held) = before.lines.get(line) else {
                shift.put_in.insert(line.clone(), names.len());
                continue;
            };
            for name in names.difference(held) {
                shift
                    .gained
                    .entry(name.clone())
                    .or_default()
                    .insert(line.clone());
            }
            for name in held.difference(names) {
                shift
                    .lost
                    .entry(name.clone())
                    .or_default()
                    .insert(line.clone());
            }
        }
        for line in before.lines.keys() {
            if !after.lines.contains_key(line) {
                shift.took_away.insert(line.clone());
            }
        }
        shift
    }

    pub(crate) fn is_empty(&self) -> bool {
        self.gained.is_empty()
            && self.lost.is_empty()
            && self.put_in.is_empty()
            && self.took_away.is_empty()
    }

    /// Every name that moved, as `(mark, name, the lines it moved on)`,
    /// fewest lines first — the flutter reads before the bulk, because
    /// the bulk is the row a reader can take on trust.
    fn moves(&self) -> Vec<(char, &String, &BTreeSet<String>)> {
        let mut moves: Vec<(char, &String, &BTreeSet<String>)> = self
            .gained
            .iter()
            .map(|(name, lines)| ('+', name, lines))
            .chain(self.lost.iter().map(|(name, lines)| ('-', name, lines)))
            .collect();
        moves.sort_by(|one, two| (one.2.len(), one.1, one.0).cmp(&(two.2.len(), two.1, two.0)));
        moves
    }

    /// Where a name moved: the verbs when they are few enough to read,
    /// and how many of the census's lines when they are not — with the
    /// one that moved them all said as all, so a new component is told
    /// from a partial move without counting.
    fn spread(&self, lines: &BTreeSet<String>) -> Vec<String> {
        if lines.len() <= NAMED_AT_MOST {
            return lines.iter().cloned().collect();
        }
        if lines.len() == self.lines {
            return vec![format!("all {} lines", self.lines)];
        }
        vec![format!("{} of {} lines", lines.len(), self.lines)]
    }

    /// The write as a block of the gate's record: one row per name that
    /// moved, and one per line put in or taken away.
    pub(crate) fn block(&self) -> String {
        if self.is_empty() {
            // No line and nothing moved is a run that never read the
            // census — a dry run — and it has nothing to say of one.
            if self.lines == 0 {
                return String::new();
            }
            return format!("  census  no line moved ({} line(s))\n", self.lines);
        }
        let mut rows: Vec<(String, String)> = Vec::new();
        // Lines are named the way a moved name's are, and past a handful
        // the header's count is the whole answer: a tree with no census
        // yet puts every line in at once, and naming them would print
        // the file back.
        if self.put_in.len() <= NAMED_AT_MOST {
            for (line, names) in &self.put_in {
                rows.push((String::from("+line"), format!("{line} ({names} name(s))")));
            }
        }
        if self.took_away.len() <= NAMED_AT_MOST {
            for line in &self.took_away {
                rows.push((String::from("-line"), line.clone()));
            }
        }
        for (mark, name, lines) in self.moves() {
            let head = format!("{mark}{name}");
            for (row, where_) in self.spread(lines).into_iter().enumerate() {
                rows.push((
                    if row == 0 {
                        head.clone()
                    } else {
                        String::new()
                    },
                    where_,
                ));
            }
        }
        let width = rows.iter().map(|(head, _)| head.len()).max().unwrap_or(0);
        let mut out = format!(
            "  census  {} name(s) moved over {} line(s){}\n",
            self.gained.len() + self.lost.len(),
            self.lines,
            self.lines_said(),
        );
        for (head, where_) in rows {
            out.push_str(&format!("          {head:width$}  {where_}\n"));
        }
        out
    }

    /// What the header says of whole lines, when there were any.
    fn lines_said(&self) -> String {
        let mut said = String::new();
        if !self.put_in.is_empty() {
            said.push_str(&format!(", {} line(s) put in", self.put_in.len()));
        }
        if !self.took_away.is_empty() {
            said.push_str(&format!(", {} taken away", self.took_away.len()));
        }
        said
    }

    /// What the write did to one verb's line, in a clause a run of that
    /// verb can print beside its own count: `(+Theme)`, `(+A -B)`, and
    /// nothing at all when the line came back the same.
    ///
    /// A name that moved on more lines than this one says how many, so
    /// the one run can tell the two writes apart without the file: a verb
    /// meeting a component it had not is its line alone, and a component
    /// the app gained or lost is every line there is.
    pub(crate) fn said_for(&self, line: &str) -> String {
        let mut own: Vec<String> = Vec::new();
        let mut beside: Vec<String> = Vec::new();
        for (mark, name, lines) in self.moves() {
            let others = lines.iter().filter(|held| *held != line).count();
            if !lines.contains(line) {
                beside.push(format!("{mark}{name} on {others} other line(s)"));
            } else if others == 0 {
                own.push(format!("{mark}{name}"));
            } else {
                own.push(format!("{mark}{name} on {} lines", lines.len()));
            }
        }
        if own.is_empty() && beside.is_empty() {
            return String::new();
        }
        let own = if own.is_empty() {
            String::from("this line unchanged")
        } else {
            own.join(" ")
        };
        if beside.is_empty() {
            return format!(" ({own})");
        }
        format!(" ({own}; {})", beside.join(", "))
    }
}

/// Records what a passing run of `line` showed. Names that are no QML
/// file of the app (C++ types, inline components, files since removed)
/// are dropped; what is left is the line, in place of whatever an earlier
/// run of it wrote — or, where the run photographed a page whose rows
/// were still arriving (`page_settled` false), added to it, because such
/// a run can say what it met and not that the rest is gone.
///
/// Answers with how many names the line holds and what the write moved
/// ([`Shift`]), so the run can say which names it is that changed rather
/// than leave a file for somebody to diff.
pub(crate) fn record(
    root: &Path,
    line: &str,
    names: &[String],
    page_settled: bool,
) -> Result<(usize, Shift), String> {
    let _turn = one_writer(root)?;
    let known = component_files(root)?;
    let before = Census::load(root);
    let mut census = Census {
        lines: before.lines.clone(),
    };
    let mut shown: BTreeSet<String> = names
        .iter()
        .filter(|n| known.contains(*n))
        .cloned()
        .collect();
    if !page_settled && let Some(held) = census.lines.get(line) {
        shown.extend(held.iter().cloned());
    }
    let count = shown.len();
    census.lines.insert(line.to_string(), shown);
    for names in census.lines.values_mut() {
        names.retain(|name| known.contains(name));
    }
    census.save(root)?;
    let shift = Shift::between(&before, &census);
    Ok((count, shift))
}

/// The file under one writer at a time, for as long as the guard lives.
/// The gate runs the verbs several at once (`gate::verbs`), and a run
/// reads the whole file, puts its own line in and writes the whole back
/// — two of those at once would each lose the other's line. The lock
/// lives under target/, which git ignores: a file beside the census
/// would be a change in the tree the gate refuses to run over.
fn one_writer(root: &Path) -> Result<crate::locks::Locked, String> {
    let dir = root.join("target");
    std::fs::create_dir_all(&dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    let path = dir.join("verb-census.lock");
    let file = std::fs::OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .truncate(false)
        .open(&path)
        .map_err(|e| format!("{}: {e}", path.display()))?;
    file.lock()
        .map_err(|e| format!("could not hold {}: {e}", path.display()))?;
    Ok(crate::locks::Locked::new(file))
}

/// The names of every QML component file of the app, product and
/// harness alike.
fn component_files(root: &Path) -> Result<BTreeSet<String>, String> {
    Ok(super::graph::qml_files(root)?
        .iter()
        .map(|f| stem_of(f))
        .collect())
}

/// Whether a QML file can stand in the item tree at all. A singleton or a
/// `QtObject` root never does, so no census can name it: its readers
/// carry it.
pub(crate) fn instantiable(root: &Path, file: &str) -> bool {
    let Ok(text) = std::fs::read_to_string(root.join(file)) else {
        return false;
    };
    if text.contains("pragma Singleton") {
        return false;
    }
    // A root nothing here can read is still a component: the one shape
    // that never stands in a tree is the one this can name.
    root_type(root, file).unwrap_or_default() != "QtObject"
}

/// What a component's own object is: the first word of the first line
/// that opens one — `Item {`, `QtObject {`, `AppCard {`.
pub(crate) fn root_type(root: &Path, file: &str) -> Option<String> {
    let text = std::fs::read_to_string(root.join(file)).ok()?;
    let code = super::graph::strip_comments(&text);
    code.lines()
        .map(str::trim)
        .find(|line| line.ends_with('{') && !line.starts_with("import") && !line.contains(':'))
        .and_then(|line| line.split_whitespace().next())
        .map(str::to_string)
}

/// Who wears whom: the stem of every component that is another one's root
/// type, against the stems that wear it.
///
/// **The census reads the item tree, which answers with the outermost type
/// only** — an item declared as a `GraphFind` says `GraphFind`, never the
/// `FindBar` it is one of. So a component used only as somebody's root can
/// never be named by a run, and the two answers the census is asked for
/// have to go through the wearer: which verbs show this file, and whether
/// any of them does. Read off the sources rather than the tree, because
/// the tree is exactly what cannot say it.
pub(crate) fn worn_by(root: &Path) -> BTreeMap<String, BTreeSet<String>> {
    let mut worn: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    let mut files = Vec::new();
    if collect(
        root,
        &root.join("crates/platitude-app/src"),
        "qml",
        &mut files,
    )
    .is_err()
    {
        return worn;
    }
    for file in &files {
        let stem = stem_of(file);
        let Some(kind) = root_type(root, file) else {
            continue;
        };
        if kind != stem {
            worn.entry(kind).or_default().insert(stem);
        }
    }
    worn
}

/// `stem` and everyone wearing it, however many layers deep.
pub(crate) fn through_wearers(
    stem: &str,
    worn: &BTreeMap<String, BTreeSet<String>>,
    out: &mut BTreeSet<String>,
) {
    if !out.insert(stem.to_string()) {
        return;
    }
    for wearer in worn.get(stem).into_iter().flatten() {
        through_wearers(wearer, worn, out);
    }
}

/// Whether the run photographed a page that had stopped arriving: the
/// `census page=` line the walk says before the names.
///
/// A run that said nothing is read as one whose rows were still on their
/// way, which is the answer that can only add names — the census of a
/// build whose harness does not say this must not lose a name to the
/// silence.
pub(crate) fn page_settled_in(lines: &[String]) -> bool {
    lines
        .iter()
        .rev()
        .find_map(|line| line.split("census page=").nth(1))
        .and_then(|rest| rest.split_whitespace().next())
        .is_some_and(|word| word == "settled")
}

/// The names a run reported: the `census=` line, comma-separated.
pub(crate) fn names_in(lines: &[String]) -> Option<Vec<String>> {
    lines
        .iter()
        .rev()
        .find_map(|line| line.split("census=").nth(1))
        .map(|rest| {
            rest.trim()
                .split(',')
                .map(str::trim)
                .filter(|n| !n.is_empty())
                .map(str::to_string)
                .collect()
        })
}

#[cfg(test)]
mod tests {
    use super::{Census, Shift, names_in, page_settled_in, record};
    use std::collections::BTreeSet;
    use std::path::PathBuf;

    /// A census of the lines given, written the way the file is.
    fn census_of(lines: &[(&str, &[&str])]) -> Census {
        let text: String = lines
            .iter()
            .map(|(line, names)| format!("{line}\t{}\n", names.join(" ")))
            .collect();
        Census::parse(&text)
    }

    /// Eight verbs showing the same two components — enough lines that a
    /// name every one of them moved is past what the rows will name.
    fn eight_lines() -> Census {
        census_of(
            &VERBS
                .iter()
                .map(|verb| (*verb, &["AppCard", "Main"][..]))
                .collect::<Vec<_>>(),
        )
    }

    /// The census those eight verbs make when each shows what `showing`
    /// gives its place.
    fn eight_showing(showing: impl Fn(usize) -> &'static [&'static str]) -> Census {
        census_of(
            &VERBS
                .iter()
                .enumerate()
                .map(|(n, verb)| (*verb, showing(n)))
                .collect::<Vec<_>>(),
        )
    }

    /// A block's rows with the column padding taken out, so a test says
    /// what a row holds and not how wide the widest name beside it was.
    fn rows(block: &str) -> Vec<String> {
        block
            .lines()
            .map(|row| row.split_whitespace().collect::<Vec<_>>().join(" "))
            .collect()
    }

    const VERBS: [&str; 8] = [
        "commit --preset basic",
        "diff-file notes.txt",
        "graph --preset tags",
        "op-exit-go continue --preset rebase-staged",
        "stash --preset basic",
        "switch --preset branches",
        "wip --preset dirty",
        "zoom --preset wide",
    ];

    #[test]
    fn a_name_every_line_moved_is_one_row_and_a_name_few_lines_moved_names_the_verbs() {
        // A component the app gained, met by every run; one verb landing
        // somewhere new, which is the flutter; and a component two verbs
        // stopped showing.
        let after = eight_showing(|n| match n {
            3 => &["AppCard", "DiffReach", "FileRowDelegate", "Main"],
            0 | 1 => &["DiffReach", "Main"],
            _ => &["AppCard", "DiffReach", "Main"],
        });
        let block = Shift::between(&eight_lines(), &after).block();
        assert_eq!(
            rows(&block),
            [
                "census 3 name(s) moved over 8 line(s)",
                // The flutter first: one verb landing where it did not
                // before, which is the row a whole-file diff loses.
                "+FileRowDelegate op-exit-go continue --preset rebase-staged",
                "-AppCard commit --preset basic",
                "diff-file notes.txt",
                // And the bulk last, counted rather than named.
                "+DiffReach all 8 lines",
            ],
            "{block}"
        );
    }

    #[test]
    fn a_name_a_subset_moved_is_counted_against_the_whole() {
        let after = eight_showing(|n| {
            if n < 7 {
                &["Main"]
            } else {
                &["AppCard", "Main"]
            }
        });
        let block = Shift::between(&eight_lines(), &after).block();
        assert_eq!(
            rows(&block),
            [
                "census 1 name(s) moved over 8 line(s)",
                "-AppCard 7 of 8 lines",
            ],
            "past a handful the verbs are counted, and a subset is not all: {block}"
        );
    }

    #[test]
    fn every_line_put_in_at_once_is_the_headers_count_and_no_rows() {
        // A tree with no census yet: every line arrives, and naming them
        // would print the file back.
        let block = Shift::between(&Census::default(), &eight_lines()).block();
        assert_eq!(
            rows(&block),
            ["census 0 name(s) moved over 8 line(s), 8 line(s) put in"],
            "{block}"
        );
    }

    #[test]
    fn a_line_put_in_or_taken_away_is_its_own_row_and_not_its_names() {
        let before = census_of(&[("wip --preset dirty", &["AppCard", "Main"])]);
        let after = census_of(&[("diff-file notes.txt", &["AppCard", "DiffPane", "Main"])]);
        let block = Shift::between(&before, &after).block();
        assert_eq!(
            rows(&block),
            [
                "census 0 name(s) moved over 1 line(s), 1 line(s) put in, 1 taken away",
                "+line diff-file notes.txt (3 name(s))",
                "-line wip --preset dirty",
            ],
            "a line that was not there gained all of its names, which the line itself \
             says: {block}"
        );
    }

    #[test]
    fn a_census_that_did_not_move_says_so_and_one_never_read_says_nothing() {
        let held = eight_lines();
        let still = Shift::between(&held, &held);
        assert!(still.is_empty());
        assert_eq!(still.block(), "  census  no line moved (8 line(s))\n");
        assert_eq!(still.said_for("wip --preset dirty"), "");
        assert_eq!(
            Shift::default().block(),
            "",
            "a dry run read no census and has nothing to say of one"
        );
    }

    /// A root holding nothing but the QML files a census may name: a
    /// checkout of one test's own, with no census in it yet.
    ///
    /// **Claimed, not merely named.** A pid and a counter name a
    /// directory that this process has not got: pids come round again,
    /// these roots are never cleaned up, and the census the last holder
    /// of the number left behind is one `Census::load` reads back as
    /// this test's own — which is how a test that asks what *no* run
    /// shows any more comes to find a line it never wrote (observed
    /// under a gate, where a side spawns processes by the dozen).
    fn root_with(components: &[&str]) -> PathBuf {
        let root = crate::verify::claim_dir(&std::env::temp_dir().join("pgg-census"), "root")
            .expect("a root of this test's own");
        let ui = root.join("crates/platitude-app/src/ui");
        std::fs::create_dir_all(&ui).expect("ui dir");
        std::fs::create_dir_all(root.join("crates/xtask")).expect("xtask dir");
        for name in components {
            std::fs::write(ui.join(format!("{name}.qml")), "Item {}\n").expect("component");
        }
        root
    }

    #[test]
    fn owes_the_verbs_whose_runs_met_a_reached_file() {
        let mut census = Census::default();
        census.lines.insert(
            "commit --preset basic".into(),
            ["CommitBox", "GraphPane"].map(String::from).into(),
        );
        census.lines.insert(
            "diff-file notes.txt".into(),
            ["DiffPane"].map(String::from).into(),
        );
        let reached: BTreeSet<String> = ["DiffPane".to_string()].into();
        assert_eq!(census.verbs_touching(&reached), vec!["diff-file notes.txt"]);
        assert!(census.covers("GraphPane"));
        assert!(!census.covers("SettingsDialog"));
    }

    #[test]
    fn reads_the_census_line_a_run_reported() {
        let lines = vec![
            "2026-09-02T01:18:33Z  INFO bench: auto_act ran=commit".to_string(),
            "2026-09-02T01:18:33Z  INFO bench: census page=settled".to_string(),
            "2026-09-02T01:18:33Z  INFO bench: census=AppCard,DiffPane,Main".to_string(),
        ];
        assert_eq!(
            names_in(&lines),
            Some(vec!["AppCard".into(), "DiffPane".into(), "Main".into()]),
            "the page line is no name, and stands in front of the names"
        );
        assert!(page_settled_in(&lines));
        assert_eq!(names_in(&[]), None);
    }

    #[test]
    fn the_terms_beside_the_answer_are_neither_a_name_nor_a_second_answer() {
        // The window says what it settled on beside the answer
        // (`WindowCensus.terms`), so both readers here have to survive
        // words they were not written for: the answer is the first of
        // them, and the names are the line that says `census=` — which
        // the answer's line, saying `census page=`, is not.
        let lines = vec![
            "INFO bench: census page=settled waited=true state=open finish=2 failed=false \
             stale=false wipRow=true wipRowStands=true"
                .to_string(),
            "INFO bench: census=AppCard,WipTallyRow".to_string(),
        ];
        assert!(page_settled_in(&lines));
        assert_eq!(
            names_in(&lines),
            Some(vec!["AppCard".into(), "WipTallyRow".into()])
        );
    }

    #[test]
    fn a_run_that_said_nothing_of_the_page_is_read_as_one_still_arriving() {
        let arriving = ["2026-09-02T01:18:33Z  INFO bench: census page=arriving".to_string()];
        assert!(!page_settled_in(&arriving));
        assert!(!page_settled_in(&[]));
    }

    #[test]
    fn a_run_writes_its_line_over_the_one_before_it() {
        let root = root_with(&["DiffPane", "GraphPane", "WipPane"]);
        record(
            &root,
            "wip --preset dirty",
            &["GraphPane".into(), "WipPane".into()],
            true,
        )
        .expect("first");
        // The verb stopped showing the graph and started showing the
        // diff: what it shows now is the whole of its line.
        let (count, shift) = record(
            &root,
            "wip --preset dirty",
            &["DiffPane".into(), "WipPane".into(), "QQuickText".into()],
            true,
        )
        .expect("second");
        assert_eq!(count, 2, "a name that is no QML file of the app is dropped");
        assert_eq!(
            shift.said_for("wip --preset dirty"),
            " (+DiffPane -GraphPane)",
            "the run says which names moved, not that the file did"
        );
        let census = Census::load(&root);
        assert_eq!(
            census.lines["wip --preset dirty"],
            ["DiffPane", "WipPane"].map(String::from).into()
        );
        assert!(!census.covers("GraphPane"), "no run shows it any more");
    }

    #[test]
    fn a_run_whose_page_was_still_arriving_only_adds() {
        let root = root_with(&["DiffPane", "GraphPane", "WipPane"]);
        record(
            &root,
            "band --system-title-bar",
            &["DiffPane".into(), "GraphPane".into()],
            true,
        )
        .expect("settled");
        // The same verb again, finished before the reads landed: the two
        // it did not meet are still what the verb shows.
        let (count, shift) = record(
            &root,
            "band --system-title-bar",
            &["GraphPane".into(), "WipPane".into()],
            false,
        )
        .expect("arriving");
        assert_eq!(count, 3);
        assert_eq!(
            shift.said_for("band --system-title-bar"),
            " (+WipPane)",
            "a run that only adds says what it added"
        );
        let census = Census::load(&root);
        assert_eq!(
            census.lines["band --system-title-bar"],
            ["DiffPane", "GraphPane", "WipPane"]
                .map(String::from)
                .into()
        );
    }

    #[test]
    fn a_component_that_is_gone_leaves_every_line() {
        let root = root_with(&["DiffPane", "WipPane"]);
        record(&root, "wip --preset dirty", &["WipPane".into()], true).expect("wip");
        record(
            &root,
            "diff-file b.txt",
            &["DiffPane".into(), "WipPane".into()],
            true,
        )
        .expect("diff");
        std::fs::remove_file(root.join("crates/platitude-app/src/ui/WipPane.qml")).expect("remove");
        let (_, shift) =
            record(&root, "diff-file b.txt", &["DiffPane".into()], true).expect("again");
        assert_eq!(
            shift.said_for("diff-file b.txt"),
            " (-WipPane on 2 lines)",
            "a name the pruning took off every line says so on the line that ran"
        );
        let census = Census::load(&root);
        assert!(!census.covers("WipPane"));
        assert_eq!(
            census.lines["wip --preset dirty"],
            BTreeSet::new(),
            "the line the run did not touch is pruned too"
        );
    }
}
